name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify the Python version you are using

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r devenv_requirements.txt

      # Step 4: Run the model script
      - name: Run model.py
        run: |
          python scripts/model.py

      # Step 5: Start the FastAPI application
      - name: Start FastAPI app
        run: |
          nohup uvicorn app.main:app --host 127.0.0.1 --port 8000 &
        shell: bash

      # Step 6: Wait for the server to start
      - name: Wait for server to start
        run: sleep 5

      # Step 7: Run tests using pytest
      - name: Run tests
        run: |
          pytest test/test.py --junitxml=report.xml

      # Optional: Collect test results
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test_log.log
